-- criando a tabela de usuários
CREATE TABLE USUARIO(
	ID				UNIQUEIDENTIFIER	NOT NULL,
	NOME			NVARCHAR(150)		NOT NULL,
	EMAIL			NVARCHAR(100)		NOT NULL UNIQUE,
	SENHA			NVARCHAR(40)		NOT NULL,
	DATAHORACRIACAO	DATETIME			NOT NULL,
	PRIMARY KEY(ID))
GO

CREATE TABLE CATEGORIA(
	ID			UNIQUEIDENTIFIER		NOT NULL,
	DESCRICAO	NVARCHAR(50)			NOT NULL,
	PRIMARY KEY(ID))
GO

INSERT INTO CATEGORIA VALUES(NEWID(), 'Despesas de casa')
INSERT INTO CATEGORIA VALUES(NEWID(), 'Cartões de crédito')
INSERT INTO CATEGORIA VALUES(NEWID(), 'Alimentação')
INSERT INTO CATEGORIA VALUES(NEWID(), 'Saúde')
INSERT INTO CATEGORIA VALUES(NEWID(), 'Lazer')
INSERT INTO CATEGORIA VALUES(NEWID(), 'Viagens')
INSERT INTO CATEGORIA VALUES(NEWID(), 'Trabalho e Renda')
INSERT INTO CATEGORIA VALUES(NEWID(), 'Outros')

CREATE TABLE CONTA(
	ID			UNIQUEIDENTIFIER		NOT NULL,
	NOME		NVARCHAR(100)			NOT NULL,
	DATA		DATE					NOT NULL,
	VALOR		DECIMAL(18,2)			NOT NULL,
	TIPO		INTEGER					NOT NULL,
	OBSERVACOES	NVARCHAR(500)			NOT NULL,
	CATEGORIAID	UNIQUEIDENTIFIER		NOT NULL,
	USUARIOID	UNIQUEIDENTIFIER		NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(CATEGORIAID) REFERENCES CATEGORIA(ID),
	FOREIGN KEY(USUARIOID) REFERENCES USUARIO(ID))
GO


